// Unofficial protobuf definition of Google Authenticator Migration exports
// Based on Google Authenticator 5.10
// Chris van Marle 04-06-2020

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package totp

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *OTPData) Default() {
}

func (x *OTPAccount) Default() {
	if x.Algorithm == nil {
		v := Algorithm(1)
		x.Algorithm = &v
	}
	if x.Digits == nil {
		v := Digit(1)
		x.Digits = &v
	}
	if x.Type == nil {
		v := OTPType(2)
		x.Type = &v
	}
}
